GameOfThronePool/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GameOfThronePool.Models;
using GameOfThronePool.Data;

namespace GameOfThronePool.Controllers
{
    public class HomeController : Controller
    {
        private readonly DeadPoolDBContext _context;
        public HomeController(DeadPoolDBContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewData["Kingdoms"] = _context.Users.ToList().Count;
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";
            
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GameOfThronePool/Controllers/MailTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using GameOfThronePool.Services;
using Microsoft.AspNetCore.Http;

namespace GameOfThronePool.Controllers
{
    public class MailTestController : Controller

    {
        private string[] admins = new string[] { "stephen@foxdeploy.com", "sred13@gmail.com" };
        private readonly IEmailSender _emailSender;

        public MailTestController(
            IEmailSender emailSender
            )
        {
            _emailSender = emailSender;

        }
        [Authorize]
        public IActionResult Index()
        {
            string username = HttpContext.User.Identity.Name;
            
            if (!(admins.Contains(username)))
            {
                return Unauthorized();
            }
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<JsonResult> Send(string toEmail, string Subject, string Body){
            string username = HttpContext.User.Identity.Name;

            if (!(admins.Contains(username)))
            {
                return Json(new {
                status = "Forbidden"
                });
            }

            await _emailSender.SendEmailConfirmationAsync("sred13@gmail.com", "https://www.foxdeploy.com");
            var response = await _emailSender.EasySendEmailWait(toEmail, Subject, Body);
            string key = _emailSender.CheckKey();
            //await _emailSender.SendEmailAsync("sred13@gmail.com", "GoT-NewUser: " + Subject, Body);

            return Json(new
            {
                fromEmail = "sred13@gmail.com",
                toEmail = toEmail,
                Subject = Subject,
                Body = Body,
                Status = response.StatusCode.ToString(),
                Key = key

            }
                );
        }
    }
}

GameOfThronePool/Controllers/ScoreBoardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using GameOfThronePool.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace GameOfThronePool.Models
{
    public class ScoreBoardController : Controller
    {
        private readonly DeadPoolDBContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private string[] admins = new string[] { "stephen@foxdeploy.com", "sred13@gmail.com" };
        string[] UsersNotToDisplay = new string[] { "sred13@foxdeploy.com", "stephenowenii@gmail.com" };
        public ScoreBoardController(DeadPoolDBContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        [Authorize]
        // GET: ScoreBoard
        public async Task<IActionResult> Index()
        {
            ViewBag.IsPrivileged = false;
            string username = HttpContext.User.Identity.Name;
            //string user = UserManager.GetUserName(User);
            if (admins.Contains(username))
            {
                ViewBag.IsPrivileged = true;
            }

            if (!_context.UserScoreRecord.Any())
            {
                StageScoreBoard(); 
            }

            string cookieValueFromContext = HttpContext.Request.Cookies["UserSeenModal"];
            //read cookie from Request object  
            string cookieValueFromReq = Request.Cookies["UserSeenModal"];

            if (cookieValueFromReq != null)
            {
                ViewBag.ShowModal = false;
            }
            else
            {
                CookieOptions option = new CookieOptions();
                option.Expires = DateTime.Now.AddDays(12);
                Response.Cookies.Append("UserSeenModal", "true", option);
                ViewBag.ShowModal = true;
            }
            
            return View(await _context.UserScoreRecord.Where(m=>!UsersNotToDisplay.Contains(m.UserName))
                .ToListAsync());
            
        }

        [Authorize]
        public async Task<IActionResult> Update()
        {
            string username = HttpContext.User.Identity.Name;
            //string user = UserManager.GetUserName(User);
            if (!admins.Contains(username))
            {
                return Unauthorized();
            }            
            return View(await _context.UserScoreRecord.ToListAsync());
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateScores()
        {
            string username = HttpContext.User.Identity.Name;
            //string user = UserManager.GetUserName(User);
            if (!admins.Contains(username))
            {
                return Unauthorized();
            }
            //todo update and reward for proper whitewalker guesses
            List<CorrectAnswers> Correct = _context.CorrectAnswers.FromSqlRaw(@"select UserName,count(distinct ShowCharacterStatusRecordID) as 'MatchingAnswers' 
                    from UserCharacterSelection as USelection
                    join ShowCharacterStatusRecord as SHOW on SHOW.CharacterName = USelection.CharacterName and SHow.AliveStatus = USelection.AliveStatus
                    group by UserName ").ToList();

            List<wrongWhiteWalkers> wrongWW= _context.wrongWhiteWalkers.FromSqlRaw(@"select UserName,count(distinct ShowCharacterStatusRecordID) as 'WrongWhiteWalkers' 
                    from UserCharacterSelection as USelection
                    join ShowCharacterStatusRecord as SHOW on SHOW.CharacterName =USelection.CharacterName and SHow.WhiteWalkerStatus != USelection.BecomesAWhiteWalker
                    where USelection.BecomesAWhiteWalker = 1
                    group by UserName").ToList();
            List<rightWhiteWalkers> rightWW = _context.rightWhiteWalkers.FromSqlRaw(@"select UserName, count(distinct ShowCharacterStatusRecordID) as 'RightWhiteWalkers'
                    from UserCharacterSelection as USelection
                    join ShowCharacterStatusRecord as SHOW on SHOW.CharacterName = USelection.CharacterName and SHow.WhiteWalkerStatus = USelection.BecomesAWhiteWalker
                    where USelection.BecomesAWhiteWalker = 1
                    group by UserName").ToList();

            List<BonusQuestions> bonus = _context.BonusQuestions.FromSqlRaw(@"select UserName, QuestionNumber 
                    from UserBonusQuestion 
                    where Correct = 1
                    group by UserName, QuestionNumber ").ToList();

            foreach (UserScoreRecord user in _context.UserScoreRecord.ToList())
            {
                user.BonusScore = 0;
                user.BaseScore = 0;
                user.TotalScore = 0;

                var thisUserBase = Correct.Where(m => m.UserName.Equals(user.UserName)).FirstOrDefault();
                var thisUserWrongWhiteWalker = wrongWW.Where(m => m.UserName.Equals(user.UserName)).FirstOrDefault();
                var thisUserRightWhiteWalker = rightWW.Where(m => m.UserName.Equals(user.UserName)).FirstOrDefault();
                List<BonusQuestions> thisUserBonus = bonus.Where(m => m.UserName.Equals(user.UserName)).ToList();
                //string msg = "updating: " + user.UserFriendlyName;
                int score = thisUserBase.MatchingAnswers;


                user.BaseScore = (thisUserWrongWhiteWalker == null) ? score : score - thisUserWrongWhiteWalker.WrongWhiteWalkers;
                user.BaseScore = (thisUserRightWhiteWalker == null) ? score : score + thisUserRightWhiteWalker.RightWhiteWalkers;

                if (thisUserBonus != null)
                {
                    foreach (BonusQuestions b in thisUserBonus)
                    {
                        if (b.QuestionNumber == 1) { user.BonusScore += 1; }
                        if (b.QuestionNumber == 2) { user.BonusScore += 2; }
                        if (b.QuestionNumber == 3) { user.BonusScore += 4; }                        
                    }
                }

                user.TotalScore = user.BonusScore + score;
                user.CreatedDate = DateTime.Now;
                _context.SaveChanges();
            }

            TempData["Message"] = "Updated scores...";
            return RedirectToAction("Update");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Restage()
        {
            string username = HttpContext.User.Identity.Name;
            //string user = UserManager.GetUserName(User);
            if (!admins.Contains(username))
            {
                return Unauthorized();
            }
            StageScoreBoard();
            TempData["Message"] = "Restaged Scores...";
            return RedirectToAction("Update");
        }

        [Authorize]
        public void StageScoreBoard()
        {
            var users = _userManager.Users.ToList();
            
            foreach (var user in users)
            {
                //check for a score record, if exists, display, if not, create
                var userScoreRecord = _context.UserScoreRecord
                .FirstOrDefault(m => m.UserFriendlyName == user.UserFriendlyName);
                if (userScoreRecord == null)
                {
                    userScoreRecord = new UserScoreRecord
                    {
                        UserFriendlyName = user.UserFriendlyName,
                        CreatedDate = DateTime.Now
                    };

                    _context.UserScoreRecord.Add(userScoreRecord);
                    _context.SaveChanges();
                }

                //check for null username and populate
                if (userScoreRecord.UserName == null)
                {
                    userScoreRecord.UserName = user.UserName;
                    _context.SaveChanges();
                }
            }
        }

        [Authorize]
        // GET: ScoreBoard/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            string username = HttpContext.User.Identity.Name;
            //string user = UserManager.GetUserName(User);
            if (!admins.Contains(username))
            {
                return Unauthorized();
            }            

            if (id == null)
            {
                return NotFound();
            }

            var userScoreRecord = await _context.UserScoreRecord
                .FirstOrDefaultAsync(m => m.UserScoreRecordID == id);
            if (userScoreRecord == null)
            {
                return NotFound();
            }

            return View(userScoreRecord);
        }

        //[Authorize]
        //// GET: ScoreBoard/Create
        //public IActionResult Create()
        //{
        //    return View();
        //}

        //// POST: ScoreBoard/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[Authorize]
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("UserScoreRecordID,UserFriendlyName,BaseScore,BonusScore,TotalScore,CreatedDate")] UserScoreRecord userScoreRecord)
        //{
        //    string username = HttpContext.User.Identity.Name;
        //    //string user = UserManager.GetUserName(User);
        //    if (!admins.Contains(username))
        //    {
        //        return Unauthorized();
        //    }

        //    if (ModelState.IsValid)
        //    {
        //        _context.Add(userScoreRecord);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }

GameOfThronePool/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

GameOfThronePool/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>The 2019 Game of Thrones Final Season Deathpool</h3>
<blockquote class="quote-card">
    <p>
        <i>
            If you think this has a happy ending, you haven't been paying attention.
        </i>
    </p>
</blockquote>
<p>
Pick your fun user name like Lord Stephen, Ser MoonBoy, whatever you want and then your e-mail and password. Please don't use your normal password for everything else. It's encrypted and I can't see it but it's better to be safe. This also means Password reset won't work, so don't lose your pw
</p>
<br />
Once you're registered, click 'Setup my DeathPool' and select whether a character is alive or dead by the end of the show. If they died you can also provide if they become a WhiteWalker or not.
<br /><br />
Finally at the bottom of the page you can answer three bonus questions for extra points.
<br />
Here's how we'll determine a winner:<br />
1 point - right about being alive or dead<br />
+1 point - gamble a point and guess if they're a White Walker or not! If you're wrong...you lose a point.<br />

Bonus questions are:<br />
1 Point - is Dany Preggers?<br />
2 Point - Who kills the Night king?<br />
4 Points - Who holds the throne at the end of the show?<br />

<address>
    <strong>Support:</strong> <a href="mailto:stephen@foxdeploy.com">Stephen@FoxDeploy.com</a><br />
</address>

GameOfThronePool/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Game of Thrones Season 8 DeadPool";
}

<style>
    h2, h4 {
        font-family: OFL Sorts Mill Goudy, Noto Nastaliq Urdu, My Noto Nastaliq Urdu, Georgia, serif;
    }
    
    body {
        padding-top: 50px;
        padding-bottom: 20px;
        font-family: Segoe UI,Frutiger,Frutiger Linotype,Dejavu Sans,Helvetica Neue,Arial,sans-serif;
    }
    .carousel-inner item {
        height: 300px;
        overflow: hidden;
        width: 100%;
    }    
    .carousel-item img {
        width: 100%;
    }

    #myCarousel > div > div.item.active > div > h3 {
        text-shadow: 2px 2px 4px #000000;
    }

    #myCarousel > div {
        text-shadow: 2px 2px 4px #000000;
    }
</style>
<h4>Join @ViewData["Kingdoms"] kingdoms already registered!</h4>
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/sansa_stark_in_game_of_thrones_final_season_8_2019-1920x1080.jpg" alt="ForTheNightIsDarkAndFullOfTerrors" />
            <div class="carousel-caption" role="option">
                <h3>
                    <a href="https://www.facebook.com/groups/375898252994350/">Split a real pool to build your own Casterly Rock!</a>
                </h3>
            </div>
        </div>
        <div class="item">
            <img src="~/images/WinterIsComing.jpg" alt="Assistant to the night king" />
            <div class="carousel-caption" role="option">
                <h3>
                    Sign in now!<br />
                    @Html.ActionLink("Register⚔", "Login", "Account", null, new { @class = "btn btn-default" })
                </h3>
            </div>
        </div>
        <div class="item">
            <img src="~/images/Targ.jpg" alt="ForTheNightIsDarkAndFullOfTerrors" />
            <div class="carousel-caption" role="option">
                <h3>
                    Join the group chat!<br />
                    <a class="btn btn-default" href="https://www.facebook.com/groups/375898252994350/">Join the chat!</a>
                </h3>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Create your Team!</h2>
        <ul>
            <li><a asp-area="" asp-controller="DeadPoolSelection" asp-action="Index">Only a few will survive</a></li>
            <li><a asp-area="" asp-controller="Home" asp-action="Contact">Rules</a></li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>Join the Group Chat!</h2>
        <ul>
            <li><a href="https://www.facebook.com/groups/375898252994350/">Join for episode discussion!</a></li>
        </ul>
    </div>

    <div class="col-md-3">
        <h2>Track who lives and dies</h2>
        <ul>
            <li><a asp-area="" asp-controller="ScoreBoard" asp-action="Index">View the current score board!</a></li>            
            <li><a asp-area="" asp-controller="SetupCharacters" asp-action="Index">View the Status of characters from the show!</a></li>
            <li><a asp-area="" asp-controller="DeadPoolSelection" asp-action="Index">View My DeathPool!</a></li>
        </ul>
    </div>
</div>

<div class="row">
<a asp-area="" asp-controller="MailTest" asp-action="Index">✉</a>
</div>