GameOfThronePool/Controllers/DeadPoolSelectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameOfThronePool.Data;
using GameOfThronePool.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace GameOfThronePool.Views.DeadPool
{
    public class DeadPoolSelectionController : Controller
    {
        private readonly DeadPoolDBContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        private string[] admins = new string[] { "stephen@foxdeploy.com", "sred13@gmail.com" };
        public DeadPoolSelectionController(DeadPoolDBContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        //internal methods
        public IEnumerable<ShowCharacterStatusRecord> GetAllCharacters()
        {
            return _context.ShowCharacterStatusRecord.ToList();
        }
        public async Task<JsonResult> SetStatusForCharAsync(int id, string Property, bool Value)
        {
            string username = HttpContext.User.Identity.Name;

            if (!(admins.Contains(username))){
                return Json(new { status = "blocked, registrations are closed!" });
            }

            var userCharacterSelection = await _context.UserCharacterSelection.FindAsync(id);
            
            if (userCharacterSelection == null)
            {
                return Json(new
                {
                    status = "recordNotFound"                    
                });
            }
            if (userCharacterSelection.UserName != username) {
                return Json(new { status = "Cannot edit someone elses record",
                    youAre = username,
                    recordBelongsTo = userCharacterSelection.UserName,
                    InputProperty = Property,
                    InputValue = Value,
                    InputID = id
                    }
                );
            }else
            {
                //if toggling the alive state
                if (Property ==  "AliveStatus")
                {
                    userCharacterSelection.AliveStatus = Value;                    
                }

                //if toggling the white walker state
                if (Property == "BecomesAWhiteWalker")
                {
                    userCharacterSelection.BecomesAWhiteWalker = Value;
                }

                try
                {
                    _context.Update(userCharacterSelection);
                    await _context.SaveChangesAsync();
                }
                catch
                {
                    return Json(NotFound());
                }
                return Json(userCharacterSelection);
            }
            /*if (HttpContext.User)

            return Json(userCharacterSelection);*/
            
        }


        public void StageNewUser(string UserName)
        {
            List<ShowCharacterStatusRecord> allCharacters = GetAllCharacters().ToList();
            foreach (ShowCharacterStatusRecord character in allCharacters)
            {
                UserCharacterSelection newUserCharacterSelection = new UserCharacterSelection();
                newUserCharacterSelection.AliveStatus = true;
                newUserCharacterSelection.BecomesAWhiteWalker = false;
                newUserCharacterSelection.CharacterName = character.CharacterName;
                newUserCharacterSelection.UserName = UserName;
                newUserCharacterSelection.CreatedDate = DateTime.Now;

                _context.UserCharacterSelection.Add(newUserCharacterSelection);
            }
            _context.SaveChanges();
            return;
        }

        public void StageNewUserQuestions(string UserName)
        {
            UserBonusQuestion newUserBonusQuestion = new UserBonusQuestion
            {
                UserName = UserName,
                QuestionNumber = 1,
                QuestionText = "Is Daenerys (Khaleesi) pregnant?",
                QuestionAnswer = null
            };

            _context.UserBonusQuestion.Add(newUserBonusQuestion);

            newUserBonusQuestion = new UserBonusQuestion
            {
                UserName = UserName,
                QuestionNumber = 2,
                QuestionText = "Who kills the Night King?",
                QuestionAnswer = null
            };

            _context.UserBonusQuestion.Add(newUserBonusQuestion);

            newUserBonusQuestion = new UserBonusQuestion
            {
                UserName = UserName,
                QuestionNumber = 3,
                QuestionText = "Who will hold the Iron Throne at the end?",
                QuestionAnswer = null
            };

            _context.UserBonusQuestion.Add(newUserBonusQuestion);

            _context.SaveChanges();
            return;
        }
        [HttpPost]
        [Authorize]
        public ActionResult Restage()
        {
            var users = _userManager.Users.ToList();
            int Restaged = 0;
            foreach (var user in users)
            {
                List<UserCharacterSelection> userRecords =  _context.UserCharacterSelection.AsQueryable().
                Where(m => m.UserName.Equals(user.UserName)).ToList();

                List<UserBonusQuestion> userQuestions = _context.UserBonusQuestion.AsQueryable().
                    Where(m => m.UserName.Equals(user.UserName)).ToList();
                if (!userRecords.Any())
                {
                    //found no records
                    StageNewUser(user.UserName);
                    Restaged = 1;
                }

                if (!userQuestions.Any())
                {
                    //found no records
                    StageNewUserQuestions(user.UserName);
                    Restaged = 1;
                }

            }
            if (Restaged == 1)
            {
                TempData["Message"] = "Created missing Records for users...";
            }            
            return RedirectToAction("Update", "ScoreBoard");
        }

        [HttpGet]
        [Authorize]
        // GET: DeadPoolSelection
        public async Task<IActionResult> Index(List<UserCharacterSelection> userRecords)
        {
            string username = HttpContext.User.Identity.Name;
            userRecords = await _context.UserCharacterSelection.AsQueryable().
                Where(m => m.UserName.Equals(username)).ToListAsync();

            List<UserBonusQuestion> userQuestions = await _context.UserBonusQuestion.AsQueryable().
                Where(m => m.UserName.Equals(username)).ToListAsync();
            if (userRecords.Any()){
                //found records
                Console.WriteLine("found records");
            }
            else
            {
                //found no records
                StageNewUser(username);
                Console.WriteLine("setting up user records");
                userRecords = await _context.UserCharacterSelection.AsQueryable().
                                Where(m => m.UserName.Equals(username)).ToListAsync();
            }

            if (userQuestions.Any())
            {
                //found records
                Console.WriteLine("found questions records");
            }
            else
            {
                //found no records
                StageNewUserQuestions(username);
                Console.WriteLine("setting up user records");
                userQuestions = await _context.UserBonusQuestion.AsQueryable().
                    Where(m => m.UserName.Equals(username)).ToListAsync();
            }

            return View(userRecords);
        }

        [HttpGet]
        [Authorize]
        // GET: DeadPoolSelection
        public async Task<IActionResult> ViewOnly(int UserScoreRecordID)
        {
            var UserScoreRecord = _context.UserScoreRecord.AsQueryable().
                Where(m => m.UserScoreRecordID.Equals(UserScoreRecordID)).FirstOrDefault();
            string username = UserScoreRecord.UserName;
            string friendlyName = UserScoreRecord.UserFriendlyName;
            List<UserCharacterSelection> userRecords = await _context.UserCharacterSelection.AsQueryable().
                Where(m => m.UserName.Equals(username)).ToListAsync();
            ViewBag.FriendlyName = friendlyName;
            return View(userRecords);
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> PostUpdate(ICollection<UserCharacterSelection> UserCharacterSelections, IFormCollection form)
        {
            int itemCount = form["item.UserCharacterSelectionID"].ToString().Split(",").Count();
            if (ModelState.IsValid)
            {
                for (int i = 0; i < itemCount; i++)
                {
                    int thisID = Convert.ToInt32(form["item.UserCharacterSelectionID"].ToString().Split(",")[i]);
                    UserCharacterSelection userCharacterSelection = _context.UserCharacterSelection.Where(m => thisID.Equals(m.UserCharacterSelectionID)).FirstOrDefault();
                    //to do, populate and update fields which changed
                    userCharacterSelection.CreatedDate = DateTime.Now;
                    userCharacterSelection.AliveStatus = (form["item.AliveStatus"].ToString().Split(",")[i] == "true") ? true : false;
                    userCharacterSelection.BecomesAWhiteWalker = (form["item.BecomesAWhiteWalker"].ToString().Split(",")[i] == "true") ? true : false;
                    //to do, add cooler checkboxes back

                    //use this syntax to update!
                    //_context.Update(userCharacterSelection);
                    //await _context.SaveChangesAsync();
                }

GameOfThronePool/Controllers/UserBonusQuestionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameOfThronePool.Data;
using GameOfThronePool.Models;

namespace GameOfThronePool.Views.DeadPoolSelection
{
    public class UserBonusQuestionsController : Controller
    {
        private string[] admins = new string[] { "stephen@foxdeploy.com", "sred13@gmail.com" };
        private readonly DeadPoolDBContext _context;

        public UserBonusQuestionsController(DeadPoolDBContext context)
        {
            _context = context;
        }
        
        // GET: UserBonusQuestions
        public async Task<IActionResult> Index()
        {
            string username = HttpContext.User.Identity.Name;
            //string user = UserManager.GetUserName(User);
            if (admins.Contains(username))
            {
                //this user is an admin
                Console.Write("user admin incoming" + username);
                return View(await _context.UserBonusQuestion.ToListAsync());
            }
            else
            {
                Console.Write("standard user" + username);
                return RedirectToAction("MyQuestions");
            }

        }

        public async Task<IActionResult> MyQuestions()
        {
            string username = HttpContext.User.Identity.Name;
            return View(await _context.UserBonusQuestion.AsQueryable().
                    Where(m => m.UserName.Equals(username)).ToListAsync());
        }

        // GET: UserBonusQuestions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userBonusQuestion = await _context.UserBonusQuestion
                .FirstOrDefaultAsync(m => m.UserBonusQuestionID == id);
            if (userBonusQuestion == null)
            {
                return NotFound();
            }

            return View(userBonusQuestion);
        }

        // GET: UserBonusQuestions/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserBonusQuestions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserBonusQuestionID,UserName,QuestionNumber,QuestionText,QuestionAnswer,Correct")] UserBonusQuestion userBonusQuestion)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userBonusQuestion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userBonusQuestion);
        }

        // GET: UserBonusQuestions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.HasPrivilege = false;
            if (id == null)
            {
                return NotFound();
            }

            var userBonusQuestion = await _context.UserBonusQuestion.FindAsync(id);
            if (userBonusQuestion == null)
            {
                return NotFound();
            }

            string username = HttpContext.User.Identity.Name;
            if (admins.Contains(username))
            {
                ViewBag.HasPrivilege = true;
            }
            return View(userBonusQuestion);
        }

        // POST: UserBonusQuestions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserBonusQuestionID,UserName,QuestionNumber,QuestionText,QuestionAnswer,Correct")] UserBonusQuestion userBonusQuestion)
        {
            if (id != userBonusQuestion.UserBonusQuestionID)
            {
                return NotFound();
            }
            string username = HttpContext.User.Identity.Name;
            if (admins.Contains(username))
            {
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(userBonusQuestion);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!UserBonusQuestionExists(userBonusQuestion.UserBonusQuestionID))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
            }
            else
            {
                return Unauthorized();
            }
            return View(userBonusQuestion);
        }

        /*/ GET: UserBonusQuestions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userBonusQuestion = await _context.UserBonusQuestion
                .FirstOrDefaultAsync(m => m.UserBonusQuestionID == id);
            if (userBonusQuestion == null)
            {
                return NotFound();
            }

            return View(userBonusQuestion);
        }

        // POST: UserBonusQuestions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var userBonusQuestion = await _context.UserBonusQuestion.FindAsync(id);
            _context.UserBonusQuestion.Remove(userBonusQuestion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        */
        private bool UserBonusQuestionExists(int id)
        {
            return _context.UserBonusQuestion.Any(e => e.UserBonusQuestionID == id);
        }
    }
}

GameOfThronePool/Views/ScoreBoard/Create.cshtml
@model GameOfThronePool.Models.UserScoreRecord

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<h4>UserScoreRecord</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserFriendlyName" class="control-label"></label>
                <input asp-for="UserFriendlyName" class="form-control" />
                <span asp-validation-for="UserFriendlyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BaseScore" class="control-label"></label>
                <input asp-for="BaseScore" class="form-control" />
                <span asp-validation-for="BaseScore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="BonusScore" /> @Html.DisplayNameFor(model => model.BonusScore)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="TotalScore" class="control-label"></label>
                <input asp-for="TotalScore" class="form-control" />
                <span asp-validation-for="TotalScore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GameOfThronePool/Views/ScoreBoard/Delete.cshtml
@model GameOfThronePool.Models.UserScoreRecord

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserScoreRecord</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserFriendlyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserFriendlyName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BaseScore)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BaseScore)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BonusScore)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BonusScore)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalScore)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalScore)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserScoreRecordID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GameOfThronePool/Views/ScoreBoard/Details.cshtml
@model GameOfThronePool.Models.UserScoreRecord

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>UserScoreRecord</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserFriendlyName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserFriendlyName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BaseScore)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BaseScore)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.BonusScore)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.BonusScore)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TotalScore)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TotalScore)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.UserScoreRecordID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GameOfThronePool/Views/ScoreBoard/Edit.cshtml
@model GameOfThronePool.Models.UserScoreRecord

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

<h4>UserScoreRecord</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="UserScoreRecordID" />
            <div class="form-group">
                <label asp-for="UserFriendlyName" class="control-label"></label>
                <input asp-for="UserFriendlyName" class="form-control" />
                <span asp-validation-for="UserFriendlyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BaseScore" class="control-label"></label>
                <input asp-for="BaseScore" class="form-control" />
                <span asp-validation-for="BaseScore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="BonusScore" /> @Html.DisplayNameFor(model => model.BonusScore)
                    </label>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="TotalScore" class="control-label"></label>
                <input asp-for="TotalScore" class="form-control" />
                <span asp-validation-for="TotalScore" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GameOfThronePool/Views/ScoreBoard/Index.cshtml
@model IEnumerable<GameOfThronePool.Models.UserScoreRecord>

@{
    bool ShowModal = ViewBag.ShowModal;
    ViewData["Title"] = "GoT 2019 - ScoreBoard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    h2, h4, th {
        font-family: OFL Sorts Mill Goudy, Noto Nastaliq Urdu, My Noto Nastaliq Urdu, Georgia, serif;
    }

    body {
        padding-top: 50px;
        padding-bottom: 20px;
        font-family: Segoe UI,Frutiger,Frutiger Linotype,Dejavu Sans,Helvetica Neue,Arial,sans-serif;
    }

        body > div.bootbox.modal.fade.bootbox-alert.in {
            margin-top: 250px;
            font-size: 16px;
            font-family: OFL Sorts Mill Goudy, Noto Nastaliq Urdu, My Noto Nastaliq Urdu, Georgia, serif;
        }
</style>
<br />
<div class="row">
    <div class="col-lg-6">
        <h2>Leaderboards</h2>
    </div>
    @if (ViewBag.IsPrivileged)
    {
        <div class="col-lg-2 pull-right">
            <a href="ScoreBoard/Update" class="btn btn-warning">
                Admin Tools
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            </a>
        </div>
    }
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                Rulers Name
            </th>
            <th>
                Points
            </th>
            <th>
                Bonus Points
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalScore)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.OrderByDescending(a => a.TotalScore))
        {
            <tr>
                <td>
                    @Html.ActionLink(@item.UserFriendlyName, "ViewOnly", "DeadPoolSelection", new { UserScoreRecordID = item.UserScoreRecordID })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BaseScore)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BonusScore)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalScore)
                </td>

            </tr>
        }
    </tbody>
</table>


<script src="~/lib/bootbox.min.js"></script>
<script src="~/lib/bootbox.locales.min.js"></script>
<i>Scores last updated at @Model.FirstOrDefault().CreatedDate</i>
@if (ShowModal) {
<script>
    bootbox.alert({
        message: "You can now view others selections!  <br>Click someone's name to see how bloodthirsty they are!",
        backdrop: true
    });
</script>
}

GameOfThronePool/Views/ScoreBoard/Update.cshtml
@model IEnumerable<GameOfThronePool.Models.UserScoreRecord>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Message = TempData["Message"];
}
<style>
    .alert-primary {
        color: #004085;
        background-color: #cce5ff;
        border-color: #b8daff;
    }
</style>
<br /><br />
<h3>Update Scores?</h3>
@if (ViewBag.Message != null)
{
    <div class="alert alert-primary" role="alert">
        @ViewBag.Message
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserFriendlyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BaseScore)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BonusScore)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalScore)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserFriendlyName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BaseScore)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BonusScore)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalScore)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedDate)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.UserScoreRecordID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.UserScoreRecordID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.UserScoreRecordID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="row">
    <div class="col-lg-3">
        @using (Html.BeginForm("Index", "UserBonusQuestions", FormMethod.Post))
        {
            <input type="submit" value="Mark Bonus Answers" class="btn btn-default" />
        }
    </div>
    <div class="col-lg-3">
        @using (Html.BeginForm("Restage", "DeadPoolSelection", FormMethod.Post))
        {
            <input type="submit" value="Stage Missing CharacterRecords" class="btn btn-info" />
        }
    </div>
    <div class="col-lg-3">
        @using (Html.BeginForm("UpdateScores", "Scoreboard", FormMethod.Post))
        {
            <input type="submit" value="Update all Scores" class="btn btn-warning" />
        }
    </div>
    
    <div class="col-lg-3">
        @using (Html.BeginForm("Restage", "Scoreboard", FormMethod.Post))
        {
            <input type="submit" value="Search for and create new Users" class="btn btn-default" />
        }

    </div>
</div>